server:
  port: ${PORT:8080}

spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://turntable.proxy.rlwy.net:17885/railway}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:owMBHOYobnjkBlWhJVzOkdjwnDZtxnZJ}
    driver-class-name: org.postgresql.Driver
    